### PR TITLE
chore: add Github action to create release PR

### PR DESCRIPTION
**Pull request by phantumcode**
- [x] PR conforms to [Pull Request](https://github.com/aws-amplify/amplify-ui-android/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guidelines.

*Issue #, if available:*

*Description of changes:*

*How did you test these changes?*
Adding Github action to automate the initial release PR with update versions for Liveness and Authenticator.
Depends on changes from this PR: https://github.com/aws-amplify/amplify-ci-support/pull/179

Release action will update the following files:
* Update the module/CHANGELOG.md
  * module changelog will ignore and exclude commits for other components based on the commit message scopes
* Update the VERSION_NAME in module/gradle.properties
* Update version used in sample app.  NOTE: the amplify version in the sample apps is not updated and will need to manually verify/update for now as part of the release PR review.
* Update module version in top-level README and module READMEs
* Update the pull request template to ensure that commit message scopes are validated

*Documentation update required?*
- [x] No
- [ ] Yes (Please include a PR link for the documentation update)

*General Checklist*
- [ ] ~Added Unit Tests~
- [ ] ~Added Integration Tests~
- [x] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mattcreaser** [comment]
UI components are released independently - it seems like this will release both at once with one version? Unless I'm missing something.

**Comment by phantumcode** [comment]
Yes, it will release both components at the same time.  I'll update it so the components are released independently.

**Comment by tylerjroach** [comment]
How is the changelog created. Ex: if we are releasing liveness is it going to inclue authenticator commits in changelog. This could be problematic when we then go to release authenticator and those changes are not included in changelog

**Comment by phantumcode** [comment]
@tylerjroach Good callout, I've updated the configuration and changelog generation so that it accounts for commit message scopes.  The changelog generation for Liveness will exclude all commits that is scoped for Authenticator and vice-versa.  All commits without a scope or isn't marked as ignored/exclude will be included by default.

**Comment by tylerjroach** [comment]
@phantumcode You may have already covered this, but as an example. Lets say we update the material 3 library.

`chore(all): Update Material3 library`

Will both the next release of liveness and authenticator include this change? Or will only the first of these released include it?  Sorry for asking so many questions, its difficult to fully understand what is being generated without seeing examples.

**Comment by phantumcode** [comment]
@tylerjroach  By default, both releases will include commits that are not part of the ignore/exclude list.  So in your example, both releases will include the `chore(all)`.  We can potentially improve that by having an explicit rule to ensure that all commits with scope of `all` or `core` always get included as well if that makes things clearer.

**Comment by phantumcode** [comment]
We could formalize this by requiring all commits to have scope of either `liveness`, `authenticator`, or `all`

**Review by tylerjroach — APPROVED** [review]

**Review by tylerjroach — APPROVED** [review]

**Review by mattcreaser — APPROVED** [review]

**Pull request merged**
